### ISSUE TITLE
Предложение

### ISSUE THREAD

**Issue by AButorov** [airens/interactive_brokers_tax#1]
Отличное начинание!
Есть предложение:
1. Дополнить инструкцию: «Отчеты должны быть только на англ. языке (русский не работает при создании файлов в директории получается не корректное имя файла).
2. Доработать макет пояснительной записки (убрать ошибки и включить опись документов предоставляемых в налоговую документов).
3. Доработать программу для других секций (например, налоги с процентов от пользования деньгами и акциями).
4. Готов оказать содействие проекту (могу программировать на Питоне).
Как связаться с Вами оставьте координаты.
Напишите мне в ответ mdscp@hotmail.com
Большое спасибо!

**Comment by airens** [comment]
Ответил на почту
