### ISSUE TITLE
Последний Python 3.9 не поддерживается

### ISSUE THREAD

**Issue by dryaz** [airens/interactive_brokers_tax#10]
Требует pandas версии 1.0.3, а она нормально не ставится.
Если убрать strict versioning, то скрипт все равно работает.

**Comment by dryaz** [comment]
https://github.com/airens/interactive_brokers_tax/pull/12

**Comment by airens** [comment]
strict versioning нужен чтобы у людей далеких от программирования все работало без танцев с бубном. Если по автоматической установке зависимостей из requirements будут ставиться последние версии, велика вероятность, что рано или поздно все это перестанет работать

**Comment by dryaz** [comment]
> strict versioning нужен чтобы у людей далеких от программирования все работало без танцев с бубном. Если по автоматической установке зависимостей из requirements будут ставиться последние версии, велика вероятность того, что рано или поздно все это перестанет работать

К сожалению, без танцев с бубном на Mac BigSur не сработает, там, кажется 3.9.1 мин. версия которая скорее всего не упадет :)

**Comment by dryaz** [comment]
Наверное, будет правильно тут просто обновить так же strict до последнего питона.

**Comment by airens** [comment]
Считаю это не проблемой скрипта, а проблемой environment, в связи с чем не вижу смысла что-то менять.
