### ISSUE TITLE
Некорректная работа с акциями у которых был reverse split

### ISSUE THREAD

**Issue by lamres** [airens/interactive_brokers_tax#17]
В отчете виден излишний НДФЛ, которого на самом деле нет (табл. 2.2.). Поскольку количество штук указывается, как до сплита (много), цена покупки изначальная до сплита (низкая), а цена продажи как после сплита (высокая). В итоге имеем большую прибыль, которой на самом деле нет.

**Comment by dryaz** [comment]
Интересно, возможно ли его вообще нормально учесть автоматически.
Думаю что даже в некоторых кейсах система подумает что шортили. Т.е. купили 4 акции, продаете 8.

**Comment by lamres** [comment]
Думаю, что лучший путь, это только когда выкачивать календарь сплитов для акций в портфеле. И если было, то там есть дата. Следовательно, понятно что было куплено до нее, и что продано после.

**Comment by airens** [comment]
У меня нет таких позиций в отчетах, поэтому заниматься я этим буду только в случае, если таковые появятся, т.к. это не секундное дело. Есть решение - давайте Pull request или хотя бы предупреждайте пользователя сообщением, что, похоже был сплит, посмотрите внимательно.

**Comment by flmnvd** [comment]
Большая часть сплитов (но почему-то не все: нет для позиций с переносом через год) есть в отчёте IB. Например:
20:25:00","EWLL(US30051D1063) Split 1 for 50 (EWLL.OLD, EWELLNESS HEALTHCARE CORP, US30051D1063)",-45000,0,0,0,
Берём соотношение "Split 1 for 50". Когда доходим в обработке до сплита, все предыдущие позиции умножаем на этот коэффициент (количество умножаем, цены делим или наоборот).
Где выкачать нормально историю сплитов пока толком не нашёл. Если найдёте - будет круто.
Так же думаю, что хорошо бы сделать типа файла проекта - там можно было бы указать вручную подобные вещи (как и остальные) и избежать интерактива во время обработки.
Я тут было свой скрипт начал писать, но думаю, что эффективнее объединить усилия.
Если никто не сделает, я в феврале допишу обработку, которая для моего отчёта отсутствует, с позволения автора. Apple даже сплитовался. Так что всё равно пригодится.

**Comment by airens** [comment]
> Большая часть сплитов (но почему-то не все: нет для позиций с переносом через год) есть в отчёте IB. Например:
> 20:25:00","EWLL(US30051D1063) Split 1 for 50 (EWLL.OLD, EWELLNESS HEALTHCARE CORP, US30051D1063)",-45000,0,0,0,
> Берём соотношение "Split 1 for 50". Когда доходим в обработке до сплита, все предыдущие не закрытые позиции умножаем на этот коэффициент (количество умножаем, цены делим или наоборот).
> Где выкачать нормально историю сплитов пока толком не нашёл. Если найдёте - будет круто.
> Так же думаю, что хорошо бы сделать типа файла проекта - там можно было бы указать вручную подобные вещи (как и остальные) и избежать интерактива во время обработки.
> Я тут было свой скрипт начал писать, но думаю, что эффективнее объединить усилия.
> Если никто не сделает, я в феврале допишу обработку, которая для моего отчёта отсутствует, с позволения автора. Apple даже сплитовался. Так что всё равно пригодится.

Автор, конечно, не против) Пока закрыл эту проблему и предупредил пользователей. Если появятся какие-то наработки - кидайте Pull Request - добавим

**Comment by lamres** [comment]
> Берём соотношение "Split 1 for 50". Когда доходим в обработке до сплита, все предыдущие не закрытые позиции умножаем на этот коэффициент (количество умножаем, цены делим или наоборот).
Главное еще не забыть предусмотреть\протестировать как прямые, так реверсные сплиты.

> Где выкачать нормально историю сплитов пока толком не нашёл. Если найдёте - будет круто.
Информация есть здесь. Можно указать тикер и слева есть таблица истории, с указанием даты события и пропорции
https://www.stocksplithistory.com/?symbol=uso
Обычное такое разбирается пакетом beautifulsoup.

**Comment by dryaz** [comment]
@airens имхо логиченее еще не решенные задачи оставлять в открытых issues, так народ, который захочет использовать будет заранее вкурсе кейсов, которые еще не обработаны.

**Comment by airens** [comment]
> @airens имхо логиченее еще не решенные задачи оставлять в открытых issues, так народ, который захочет использовать будет заранее вкурсе кейсов, которые еще не обработаны.

Народ, который пользуется данным скриптом, в большинстве своем, обычные люди, которые не знают, что такое issues и кейсы, поэтому, специально для них, в описании я написал о том, что такие операции на данный момент не поддерживаются

**Comment by dryaz** [comment]
> > @airens имхо логиченее еще не решенные задачи оставлять в открытых issues, так народ, который захочет использовать будет заранее вкурсе кейсов, которые еще не обработаны.
> 
> Народ, который пользуется данным скриптом, в большинстве своем, обычные люди, которые не знают, что такое issues и кейсы, поэтому, специально для них, в описании я написал о том, что такие операции на данный момент не поддерживаются

Оно то ясно, просто непонятно, зачем открытый тикет с внятной историей закрывать нерешенным :)
