### ISSUE TITLE
Отчеты

### ISSUE THREAD

**Issue by konclave** [airens/interactive_brokers_tax#23]
Спасибо за скрипт! Я, правда, еще не отправил отчёт, но, надеюсь, он мне сильно облегчит задачу.
В сформированном документе в конце есть список прилагаемых к отчету документов. 
А можете, пожалуйста, вписать в README, какому из отчетов в IB соответсвует каждый пункт?
Со справкой и договором примерно понятно (хотя у меня в отчетах они идут либо в одном документе, либо только справка, отдельно договора нет), а вот платежные поручения – это pdf версия того отчета, на основе которого генерируется пояснительная записка?

**Comment by airens** [comment]
Платежные поручения получайте в банке, откуда переводили деньги. В личном кабинете IB есть все остальное. Если не можете найти самостоятельно - пользуйтесь Яндексом или техподдержкой, к скрипту это отношения не имеет.
