### ISSUE TITLE
Поддержка шортов

### ISSUE THREAD

**Issue by mzaprudin** [airens/interactive_brokers_tax#24]
Валерий, здравствуйте!

Озадачился заполнением декларации для налоговой
Нашел ваш чудесный скрипт, все красиво делает, благодарю за проделанную работу!
Не хватает поддержки шортов, хочу внести изменения чтобы такие операции тоже поддерживались
Подскажите, как это лучше сделать, на что обратить внимание?

**Comment by airens** [comment]
Здравствуйте, попробуйте посмотреть на функцию trades_calc, но включать такие правки в основную ветку я не буду, так что рекомендую забрать себе код fork'ом и править уже его
