### ISSUE TITLE
Некорректно считается доход от акций

### ISSUE THREAD

**Issue by woodholly** [airens/interactive_brokers_tax#25]
Спасибо за полезную программу!

То что в шаблоне называется как "доход от продажи ценных бумаг ({{income_rub_sum}} руб.)" на самом деле доходом не является, а является налоговой базой (без учёта комиссий брокера).
Так делать нельзя, в 3-НДФЛ доход это полный доход, нельзя указывать в 2-НДФЛ в качестве дохода уже посчитанную налоговую базу. Это ошибка.
Как это правильно считать:
1) Доход от акций это полная выручка от продажи акций (1530)
2) Вычетом является стоимость покупки этих акций плюс комиссии брокера (201)
В шаблоне нужно нарисовать эти две цифры которые будут потом добавлены в 3-НДФЛ.

@airens можете это исправить ? Я пробовал сделать сам, но питон сильнее меня.

**Comment by airens** [comment]
С чего вы взяли, что это ошибка? Я и многие люди подавали декларацию в таком виде и все ок.

**Comment by woodholly** [comment]
Это ошибка, потому что доходы с кодом 1530 это полные доходы от акций без вычета, все вычеты должны быть в 201.
А принимали декларации только по невнимательности или снисхоидтельности налогового инспектора.

**Comment by woodholly** [comment]
дописал

**Comment by airens** [comment]
да, вижу теперь, посмотрю, как можно поправить

**Comment by airens** [comment]
Посмотрите. У меня сумма налога сошлась до копейки с предыдущим вариантом, поэтому, думаю, налоговая и не придиралась

**Comment by woodholly** [comment]
Всё отлично, теперь считает как надо!
