### ISSUE TITLE
Бинарный шаблон непрактичен

### ISSUE THREAD

**Issue by woodholly** [airens/interactive_brokers_tax#26]
Думаю многие пользуются программой и вносят свои изменения и страдают от того, что шаблон является бинарником (template.docx).
Такой формат шаблона не даёт возможности увидеть в коммитах какие правки в него были внесены и не даёт добавить / убрать свои правки при необходимости. git mergetool конечно не работает. Это ведёт к тому что люди не хотят (и не могут) пулить свои патчи.
С этой проблемой столкнулся и я при последнем обновлении, пришлось шаблон копировать и пределывать всё с нуля, у меня соответственно тоже бинарник.
Можно ли как-то сделать шаблон в виде текста ? К примеру создавать его из html или генерировать docx с помощью кода на питоне?

**Comment by airens** [comment]
Иных способов сделать документ, который можно будет слегка подправить и сразу отправлять в налоговую я не знаю. Шаблон я сделал специально для того, чтобы каждый мог переделать его под себя, а свой шаблон в репозитории я менять не собираюсь, т.к. он меня полностью устраивает.
