### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by GreenX5** [airens/interactive_brokers_tax#27]
File "D:\pythonProject\test3.py", line 90, in get_crs_tables
  df = pd.read_excel(response.content).rename(columns={"data": "date", "curs": "val"})

for elem in self.tree.iter() if Element_has_iter else self.tree.getiterator():
AttributeError: 'ElementTree' object has no attribute 'getiterator'

**Comment by airens** [comment]
См. Readme
