### ISSUE TITLE
Дробные акции

### ISSUE THREAD

**Issue by rjdgtn** [airens/interactive_brokers_tax#34]
В 2020 году IB добавил возможность торговать дробными акциями. Для позиций где участвовали дробные акции выдается ошибка:
"Актив продан в большем количестве, чем покупался. Операции SHORT не поддерживаются."
Дело способе обработки сделок по одной акции....
`for _ in range(int(abs(quantity))):`

**Comment by airens** [comment]
Исправляйте, делайте Pull request

**Comment by airens** [comment]
См. Readme

**Comment by rjdgtn** [comment]
Ок, так и сделаю
