### ISSUE TITLE
Сделки без комиссии

### ISSUE THREAD

**Issue by rjdgtn** [airens/interactive_brokers_tax#35]
Выглядит. что удалять все записи без комиссии не совсем верно. У меня в отчете есть сделки со значением 0 в позиции Comm/Fee в результате чего они выкидываются. Может быть есть более удачный способ фильтровать записи о сделках?

```
    if "Trades" in data:
        trades = data["Trades"]
        trades.columns = [col.lower() for col in trades]
        trades = trades.rename(columns={"comm/fee": "fee", "date/time": "date", "t. price": "price", "comm in usd":"fee"})
        trades = trades[trades.header == "Data"]
        trades = trades[trades.fee < 0]                          #  <- здесь
        trades.date = pd.to_datetime(trades.date)
    else:
```

**Comment by airens** [comment]
Опять же, у меня нет таких бумаг, если придумаете более правильный вариант - делайте Pull request

**Comment by airens** [comment]
См. Readme

**Comment by rjdgtn** [comment]
Окей, я постараюсь что-нибудь придумать, подскажи только почему фильтрации по `trades.header == "Data"` не достаточно? Есть какой-то особый смыл откидывать именно сделки без комиссии?
