### ISSUE TITLE
FIFO/LIFO

### ISSUE THREAD

**Issue by flmnvd** [airens/interactive_brokers_tax#4]
Приветствую!
В шаблоне указано, что расчёт производится методом FIFO.
Хотелось бы уточнить почему выбран FIFO?
FIFO помогает уменьшить налогооблагаемую базу?
Насколько я понимаю, выбор порядка реализации свободный.
За LIFO у меня следующие аргументы:
- однодневный трейд (купили и продали тем же днём) происходит без валютной разницы;
- возможны бонусы за удержание актива (например налоговые льготы при удержании акций РФ);

То есть вроде бы LIFO выглядит более логично.

Не могли бы Вы пояснить этот вопрос, пожалуйста?

**Comment by airens** [comment]
Здравствуйте, когда я писал этот скрипт, налоговое законодательство требовало FIFO и это прямым текстом было указано в законе, если что-то изменилось - давайте ссылку на статью НК, будем разбираться. По поводу ваших аргументов:
1. Меня НЕ интересуют однодневные сделки в принципе (в описании скрипта написано, почему)
2. Льготы на инструменты, не торгующиеся в РФ не распространяются, а заводить счет в США, чтобы покупать инструменты, которые гораздо дешевле и проще купить в РФ - ну, это такое себе.
Как раз таки именно метод FIFO для операций с ценными бумагами самый логичный и правильный. Им же пользуются все Российские брокеры.
