### ISSUE TITLE
TypeError: loop of ufunc does not support argument 0 of type float which has no callable rint method

### ISSUE THREAD

**Issue by AlexAvsenev** [airens/interactive_brokers_tax#43]
res["tax_paid"] = -div_tax["amount"].values.round(2) if div_tax is not None else 0
    
    Падает на этой строчке и начинает работать только если поменять на  res["tax_paid"] = 0
    
    Я пока плохо разбираюсь в Python и не знаю как поправить
    
Ругается следующим образом:

Расчет таблицы дивидендов...
AttributeError: 'float' object has no attribute 'rint'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Broker\1\ib.py", line 385, in <module>
    div_res = div_calc()
  File "C:\Broker\1\ib.py", line 375, in div_calc
    res["tax_paid"] = -div_tax["amount"].values.round(2) if div_tax is not None else 0
TypeError: loop of ufunc does not support argument 0 of type float which has no callable rint method

**Comment by mephy1** [comment]
round() не принимает нули для округления.
Я добавил на 378 строку astype(np.double), помогло.

res["tax_paid"] = -div_tax["amount"].values.astype(np.double).round(2) if div_tax is not None else 0

**Comment by airens** [comment]
> round() не принимает нули для округления. Я добавил на 378 строку astype(np.double), помогло.
> 
> res["tax_paid"] = -div_tax["amount"].values.astype(np.double).round(2) if div_tax is not None else 0

спасибо, добавил

**Comment by revic50** [comment]
Та же ошибка:

```
AttributeError: 'float' object has no attribute 'rint'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\interactive_brokers_tax-master\ib.py", line 383, in <module>
    div_res = div_calc()
              ^^^^^^^^^^
  File "D:\interactive_brokers_tax-master\ib.py", line 374, in div_calc
    res["tax_paid"] = -div_tax["amount"].values.round(2) if div_tax is not None else 0
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: loop of ufunc does not support argument 0 of type float which has no callable rint method
```
