### ISSUE TITLE
Вопрос по tbl_cashflow

### ISSUE THREAD

**Issue by hh-h** [airens/interactive_brokers_tax#5]
Привет, допиливаю твой скрипт, возник вопрос по `tbl_cashflow`. Переменная передается в рендер шаблона, но никак не используется, какой был в этом смысл? Вот место https://github.com/airens/interactive_brokers_tax/blob/f18f523573df36f4df48561d6a5d72a747555d60/ib.py#L567
И еще один вопрос, зачем вот этот блок? https://github.com/airens/interactive_brokers_tax/blob/f18f523573df36f4df48561d6a5d72a747555d60/ib.py#L303-L319
Спасибо!

**Comment by airens** [comment]
Привет! Это заготовка для отчета по движению денежных средств, который теперь тоже нужно подавать. Поскольку от налоговой, на момент написания скрипта, никакой формы на эту тему не было, в шаблоне эти данные пока не используются

**Comment by hh-h** [comment]
Как я понимаю это вот эта штука (последняя страница)? http://publication.pravo.gov.ru/File/GetFile/0001201512220008?type=pdf
 Ее вроде нужно отдельно заполнять через ЛК налогоплательщика.

**Comment by airens** [comment]
Да. Думаю, будет правильно добавить в пояснительную записку эту таблицу (чтобы удобнее было заполнять форму) с расчетом остатка (по курсу доллара на соответствующие даты)

**Comment by hh-h** [comment]
Понял, спасибо.
