### ISSUE TITLE
Не пропускать все уплаченные налоги, если размер таблиц не совпадает

### ISSUE THREAD

**Issue by dryaz** [airens/interactive_brokers_tax#6]
Сейчас 

```python
if div.shape[0] != div_tax.shape[0]:
            print("Размеры таблиц дивидендов и налогов по ним не совпадают. Налог на дивиденды будет 13%")
```

У меня в отчете от IBKR почему-то некоторые дивы указаны как уплаченные, дальше возвращенные и снова уплаченные, например для HHR. 

Логично было бы выдать уведомление какие конкретно позиции вызывают подозрение, а все остальные корректно посчитать.

**Comment by hh-h** [comment]
Привет, я пофиксил это в своей версии скрипта, но так как у меня очень много рефакторинга, я не могу выложить :)  
Попробуй вот этот кусок вставить, вроде эту часть не аффектят мои изменения.  
```python
        if div.shape[0] != div_tax.shape[0]:
            print("Размеры таблиц дивидендов и налогов по ним не совпадают. Попробуем исправить...")
            df = pd.DataFrame(columns=div_tax.columns)
            for index, row in div.iterrows():
                tax_row = div_tax[(div_tax["date"] == row["date"]) & (div_tax["ticker"] == row["ticker"])]
                if not tax_row.empty:
                    df.loc[index] = tax_row.T.squeeze()
                else:
                    df.loc[index] = pd.Series({
                        "withholding tax": "Withholding Tax",
                        "header": "Data",
                        "currency": div["currency"],
                        "date": div["date"],
                        "ticker": row["ticker"],
                        "amount": np.rint(0),
                        "code": np.nan,
                    })
            div_tax = df
```

**Comment by airens** [comment]
Просьба @dryaz проверить, т.к. у меня нет таких отчетов. Если все нормально - добавлю

**Comment by dryaz** [comment]
@airens гляну на досуге, спс.
Если угодно, могу поделиться отчетами, там видно как раз что не так конкретно.

**Comment by dryaz** [comment]
@hh-h `np` - такой переменной в этом вселенной скрипта кажется нет )

**Comment by hh-h** [comment]
Да, это `numpy`, он установлен зависимостями, напиши в начале `import numpy as np`

**Comment by dryaz** [comment]
> import numpy as np

Как можно заметить - я не мастрер питона))

А по факту, у тебя, кажется, должен быть еще парсинг tickera, потому что по таблице - там только description из которого, можно вытащить тикер.

**Comment by hh-h** [comment]
да, действительно, у меня там препроцессинг еще есть немного, мой скрипт не готов пока для публикации, но я могу запустить с твоим отчетом, скидывай на forjob[at]thetrue.name, если интересует такой вариант.

**Comment by dryaz** [comment]
<img width="1019" alt="CleanShot 2021-01-15 at 22 24 12@2x" src="https://user-images.githubusercontent.com/1395176/104769554-855fa380-5780-11eb-8b5c-01cdc9489839.png">
<img width="988" alt="CleanShot 2021-01-15 at 22 23 41@2x" src="https://user-images.githubusercontent.com/1395176/104769562-87c1fd80-5780-11eb-8cb0-0853a339b852.png">

Не могу пока понять почему так странно рассчитываются налоги +-38 и +38

**Comment by hh-h** [comment]
@dryaz Запушил свою версию скрипта, можешь попробовать работает ли. К сожалению, сюда присылать фикс не буду, потому что не хочется холиварить насчет качества кода :)

**Comment by hh-h** [comment]
Что-то @airens закинул нерабочий код, через такое я не могу пройти мимо :D https://github.com/airens/interactive_brokers_tax/pull/20

**Comment by airens** [comment]
> Что-то @airens закинул нерабочий код, через такое я не могу пройти мимо 😆 #20

?

**Comment by hh-h** [comment]
Мы же здесь в ветке обсудили, что мой кусок кода который я скинул нельзя просто взять и вставить, а ты так и сделал. Вот к этому мой комментарий.

**Comment by airens** [comment]
> Мы же здесь в ветке обсудили, что мой кусок кода который я скинул нельзя просто взять и вставить, а ты так и сделал. Вот к этому мой комментарий.

ну так не нужно выкладывать нерабочие куски кода, которые я не могу проверить.
