### ISSUE TITLE
Использование "стратегий" от IBKR ломает генерацию отчета

### ISSUE THREAD

**Issue by dryaz** [airens/interactive_brokers_tax#7]
Если использовать strategy в ibkr, то при генерации найдется еще одна графа `Trades`, таблица которой имеет другую схему.

Пока локально решилось пропуском таблицы, если третий столбец имеет определенное название:

split_report:
```python
if section == "Trades" and column =="Account":
                line = file.readline()
                continue
```

**Comment by dryaz** [comment]
https://github.com/airens/interactive_brokers_tax/pull/13

**Comment by airens** [comment]
добавил, в следующей версии будет, спасибо
