### ISSUE TITLE
Открытая позиция не переходит "через год"

### ISSUE THREAD

**Issue by dryaz** [airens/interactive_brokers_tax#8]
Есть тикер XXX.
В 2019 купил 7 лотов. 
В 2019 продал 2 лота.

Итого на конце 2019 года осталось 5 лотов.

В 2020 продал оставшиеся 5 лотов.

Скрипт говорит, что Short не поддерживается.

В сгенеренной папке Trades от 2019 ясно показывает, что было куплено 7 и продано 2, т.е. есть знание о том, что 5 шт. осталось на конец года, которое можно использовать для дальнейшего расчета налоговой базы.

**Comment by dryaz** [comment]
https://github.com/airens/interactive_brokers_tax/pull/13

**Comment by airens** [comment]
Проверил у себя - все переходит и рассчитывается корректно. Может быть в ваших отчетах есть какие-то особенности?

**Comment by dryaz** [comment]
Есть шанс, что вот это на самом деле причина:
https://github.com/airens/interactive_brokers_tax/issues/7

Видимо, где-то в недрах генеренных csv отчетов что-то не сошлось, по-этому, по сути все позы, которые были в стратегии не нашлись как покупки.

А с переходом через год, я кажется погорячился и он, видимо и правда должен работать.

**Comment by dryaz** [comment]
@airens оказалось проще - не было сортировки по дате.
Т.е. таблица у меня получилась таким способом, что позиции по очередности шли

2019
Buy 10
Sell 5

2020
Buy 4
Sell 10

Обрабатывалось для 2020 начиная с него. Получалось что я купил 4, пытался продать 10. И только потом оставалось 5 с прошлого года.

**Comment by dryaz** [comment]
https://github.com/airens/interactive_brokers_tax/pull/19
