### ISSUE TITLE
Trades при обмене валют имеет другую схему

### ISSUE THREAD

**Issue by dryaz** [airens/interactive_brokers_tax#9]
<img width="1269" alt="CleanShot 2020-12-30 at 16 26 05@2x" src="https://user-images.githubusercontent.com/1395176/103354140-c89cef80-4abb-11eb-8062-ea269fd718d7.png">

При выгрузке произвольного отчета на год в него попадают также сделки по обмену валюты.
Кроме того, что они корректно не отобразаться - они ломают генерацию, потому что заголовок таблицы не fee/comm а comm in usd

Пока лечится локально через переименование и этого заголовка:

```python
trades = trades.rename(columns={"comm/fee": "fee", "date/time": "date", "t. price": "price", "comm in usd":"fee"})
```

**Comment by dryaz** [comment]
https://github.com/airens/interactive_brokers_tax/pull/11

**Comment by airens** [comment]
Cпасибо добавил
